name: flutter_cwa_plugin
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  cli_util: ^0.4.1
  cwa_plugin_core:
    path: /Users/codewave/Desktop/projects/cli/cwa_plugin_core
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
