name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.GIT_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Setup custom SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host gitlab.com-codewave" >> ~/.ssh/config
          echo "    HostName gitlab.com" >> ~/.ssh/config
          echo "    User git" >> ~/.ssh/config
          echo "    IdentityFile $(pwd)/ssh_key" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/config
          chmod 600 $(pwd)/ssh_key

      - name: Setup SSH for GitLab Access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}

      - name: Install dependenciesc
        run: dart pub get

      - name: Compile to executable
        run: dart compile exe bin/flutter_cwa_plugin.dart -o bin/flutter_cwa_plugin_${{ runner.os }}_executable

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-executable
          path: bin/${{ runner.os }}_executable
