name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable

      - name: Setup SSH for GitLab Access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}

      - name: Install dependencies
        run: dart pub get

      - name: Compile to executable
        run: dart compile exe bin/main.dart -o bin/${{ runner.os }}_executable

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-executable
          path: bin/${{ runner.os }}_executable
